apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wp-db-secret
  namespace: wordpress
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: wp-db-secret          # Kubernetes secret name
    creationPolicy: Owner
  data:
    - secretKey: DB_NAME
      remoteRef:
        key: wordpress/db
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: wordpress/db
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: wordpress/db
        property: DB_PASSWORD
    - secretKey: DB_HOST
      remoteRef:
        key: wordpress/db
        property: DB_HOST
