apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-external
subsets:
  - addresses:
      - ip: 10.0.X.Y  # <-- replace with MySQL EC2 private IP
    ports:
      - name: mysql
        port: 3306
