apiVersion: v1
kind: Secret
metadata:
  name: wp-db-secret
  namespace: wordpress
type: Opaque
stringData:
  WORDPRESS_DB_NAME: wordpress_db
  WORDPRESS_DB_USER: wp_user
  WORDPRESS_DB_PASSWORD: admin@obelion
  WORDPRESS_DB_HOST: mysql-external.wordpress.svc.cluster.local:3306
